### ISSUE TITLE
go mod: unexpected module path "p3lib"

### ISSUE THREAD

**Issue by derlaft** [hashmatter/p3lib#35]
Hello over there,

I am trying to include this repository to my code using p3lib and have a trouble doing that:

```
% go build .
go: github.com/hashmatter/p3lib@v0.0.0-20190725202400-f1d0c92114a3: parsing go.mod: unexpected module path "p3lib"
go: error loading module requirements
```

I think it is probably because `go.mod` currently has `module p3lib`, but not `module github.com/hashmatter/p3lib`, but I am not yet completely sure.

Steps to reproduce:

1. Create a new empty `go mod` project.
2. Try to `github.com/hashmatter/p3lib/sphinx`
3. Get this error.

Thank you.

**Comment by gpestana** [comment]
Thanks, merged #36
